#pragma once
#define IGP_STR_PRESS_5_GET		0
#define IGP_STR_PRESS_5_VISIT		1
#define IGP_STR_WH_TITLE		2
#define IGP_STR_WH_1		3
#define IGP_STR_WH_2		4
#define IGP_STR_WH_3		5
#define IGP_STR_WH_4		6
#define IGP_STR_WH_MORE		7
#define IGP_STR_BS_TITLE		8
#define IGP_STR_BS_1		9
#define IGP_STR_BS_2		10
#define IGP_STR_BS_3		11
#define IGP_STR_BS_4		12
#define IGP_STR_BS_MORE		13
#define IGP_STR_CATALOG_TITLE		14
#define IGP_STR_COMPLETE_CATALOGUE		15
#define IGP_STR_ADS_1		16
#define IGP_STR_ADS_2		17
#define IGP_STR_ADS_3		18
#define IGP_STR_OPENBROWSER		19
#define IGP_STR_COPYRIGHT_GL		20
#define IGP_STR_RESET_POP		21
#define IGP_STR_BACK		22
#define IGP_STR_SELECT		23
#define IGP_STR_YES		24
#define IGP_STR_NO		25
#define IGP_STR_PLAY_FOR_FREE		26
